// pages/terms.tsx

import Head from 'next/head';

export default function Terms() {
  return (
    <section className='bg-gray-50'>
      <Head>
        <title>Treebazaar Terms of Use</title>
        <meta name="description" content="Terms and Conditions for using Treebazaar website and services." />
      </Head>

      <main className="bg-white min-h-screen py-10 px-4">
        <div className="max-w-4xl mx-auto bg-white shadow-md rounded-lg p-6">
          <h1 className="text-3xl font-bold mb-4">Terms and Conditions</h1>
          <h2 className="text-xl font-semibold mb-4">Treebazaar Terms of Use</h2>

          <p className="font-medium text-gray-700 mb-4">
            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under
            as applicable and the amended provisions pertaining to electronic records in various statutes as amended
            by the Information Technology Act, 2000. This electronic record is generated by a computer system and does
            not require any physical or digital signatures.
          </p>

          <p className="font-medium text-gray-700 mb-6">
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
            (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
            and Terms of Use for access or usage of www.Treebazaar.com website.
          </p>

          <p className="mb-4">
            The domain name www.Treebazaar.com (hereinafter referred to as &quot;Website&quot;) is owned by Treebazaar Internet Private Limited,
            a company incorporated under the Companies Act, 1956 with its registered office at Vaishnavi Summit, Ground Floor,
            7th Main, 80 Feet Road, 3rd Block, Koramangala Industrial Layout, Next to Wipro office, Corporation Ward No. 68,
            Koramangala, Bangalore - 560 034, Karnataka, India (hereinafter referred to as &quot;Treebazaar&quot;).
          </p>

          <p className="mb-4">
            Your use of the Website and services and tools are governed by the following terms and conditions
            (<strong>&quot;Terms of Use&quot;</strong>) as applicable to the Website including the applicable policies which are
            incorporated herein by way of reference. If You transact on the Website, You shall be subject to the policies
            that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting
            with Treebazaar Internet Private Limited and these terms and conditions including the policies constitute Your
            binding obligations, with Treebazaar.
          </p>

          <p className="mb-4">
            For the purpose of these Terms of Use, wherever the context so requires <strong>&quot;You&quot;</strong> or <strong>&quot;User&quot;</strong>
            shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data
            while registering on the Website as a Registered User using the computer systems. Treebazaar allows the User to surf the
            Website or make purchases without registering on the Website. The term <strong>&quot;We&quot;</strong>, <strong>&quot;Us&quot;</strong>,
            <strong>&quot;Our&quot;</strong> shall mean Treebazaar Internet Private Limited.
          </p>

          <p className="mb-4">
            When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews,
            Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service,
            and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this
            Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use,
            at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically
            for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and
            agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive,
            non-transferable, limited privilege to enter and use the Website.
          </p>

          <p className="mt-6 font-semibold text-gray-800 uppercase">
            Accessing, browsing or otherwise using the site indicates your agreement to all the terms and conditions under
            these terms of use, so please read the terms of use carefully before proceeding.
          </p>

          <p className="mt-2">
            By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Treebazaar Policies
            (including but not limited to Privacy Policy available on /s/privacypolicy) as amended from time to time.
          </p>
        </div>
      </main>
    </section>
  );
}
